extends Node
## The game's one typeface: a 5x7 bitmap font generated by tools/gen_font.py.
## Loaded once and applied as the window theme so every Control picks it up
## without each one asking.
##
## The type scale lives in UITheme with the rest of the design tokens.
var font: FontFile = null

func _ready() -> void:
	font = FontFile.new()
	var err: int = font.load_bitmap_font("res://ui/font/pixel.fnt")
	if err != OK:
		push_error("PixelFont: could not load pixel.fnt (%d)" % err)
		font = null
		return
	var theme := Theme.new()
	theme.default_font = font
	theme.default_font_size = UITheme.BODY
	get_tree().root.theme = theme
